export const ChampionClasses = {
  Aatrox: "juggernaut",
  Ahri: "burst",
  Akali: "assassin",
  Akshan: "marksman",
  Alistar: "vanguard",
  Amumu: "vanguard",
  Anivia: "battlemage",
  Annie: "burst",
  Aphelios: "marksman",
  Ashe: "marksman",
  AurelionSol: "battlemage",
  Azir: "battlemage",
  Bard: "catcher",
  Belveth: "skirmisher",
  Blitzcrank: "catcher",
  Brand: "burst",
  Braum: "warden",
  Briar: "diver",
  Caitlyn: "marksman",
  Camille: "diver",
  Cassiopeia: "battlemage",
  Chogath: "vanguard",
  Corki: "marksman",
  Darius: "juggernaut",
  Diana: "assassin",
  Draven: "marksman",
  DrMundo: "juggernaut",
  Ekko: "assassin",
  Elise: "diver",
  Evelynn: "assassin",
  Ezreal: "marksman",
  FiddleSticks: "battlemage",
  Fiora: "skirmisher",
  Fizz: "assassin",
  Galio: "warden",
  Gangplank: "skirmisher",
  Garen: "juggernaut",
  Gnar: "vanguard",
  Gragas: ["burst", "vanguard"],
  Graves: ["marksman", "skirmisher"],
  Gwen: "skirmisher",
  Hecarim: "diver",
  Heimerdinger: "battlemage",
  Illaoi: "juggernaut",
  Irelia: "diver",
  Ivern: "catcher",
  Janna: "enchanter",
  JarvanIV: "diver",
  Jax: "skirmisher",
  Jayce: "artillery",
  Jhin: "marksman",
  Jinx: "marksman",
  Kaisa: "marksman",
  Kalista: "marksman",
  Karma: ["enchanter", "battlemage"],
  Karthus: "battlemage",
  Kassadin: "assassin",
  Katarina: "assassin",
  Kayle: "marksman",
  Kayn: "skirmisher",
  Kennen: "burst",
  Khazix: "assassin",
  Kindred: "marksman",
  Kled: "skirmisher",
  KogMaw: ["marksman", "artillery"],
  KSante: "warden",
  Leblanc: "assassin",
  LeeSin: "diver",
  Leona: "vanguard",
  Lillia: "skirmisher",
  Lissandra: "burst",
  Lucian: "marksman",
  Lulu: "enchanter",
  Lux: "burst",
  Malphite: "vanguard",
  Malzahar: "battlemage",
  Maokai: "vanguard",
  MasterYi: "skirmisher",
  Milio: "enchanter",
  MissFortune: "marksman",
  MonkeyKing: "diver",
  Mordekaiser: "juggernaut",
  Morgana: "catcher",
  Nami: "enchanter",
  Nasus: "juggernaut",
  Nautilus: "vanguard",
  Neeko: ["burst", "catcher"],
  Nidalee: ["artillery", "diver"],
  Nilah: ["marksman", "skirmisher"],
  Nocturne: ["assassin", "diver"],
  Nunu: "vanguard",
  Olaf: "diver",
  Orianna: "burst",
  Ornn: "vanguard",
  Pantheon: "diver",
  Poppy: "warden",
  Pyke: "assassin",
  Qiyana: "assassin",
  Quinn: "marksman",
  Rakan: "catcher",
  Rammus: "vanguard",
  RekSai: "diver",
  Rell: "vanguard",
  Renata: "enchanter",
  Renekton: "diver",
  Rengar: "assassin",
  Riven: "skirmisher",
  Rumble: "battlemage",
  Ryze: "battlemage",
  Samira: "marksman",
  Sejuani: "vanguard",
  Senna: "marksman",
  Seraphine: ["enchanter", "burst"],
  Sett: "juggernaut",
  Shaco: "assassin",
  Shen: "warden",
  Shyvana: "juggernaut",
  Singed: "juggernaut",
  Sion: "vanguard",
  Sivir: "marksman",
  Skarner: "vanguard",
  Sona: "enchanter",
  Soraka: "enchanter",
  Swain: "battlemage",
  Sylas: ["burst", "skirmisher"],
  Syndra: "burst",
  TahmKench: "warden",
  Taliyah: "battlemage",
  Talon: "assassin",
  Taric: ["enchanter", "warden"],
  Teemo: "battlemage",
  Thresh: "catcher",
  Tristana: "marksman",
  Trundle: "juggernaut",
  Tryndamere: "skirmisher",
  TwistedFate: "burst",
  Twitch: "marksman",
  Udyr: "juggernaut",
  Urgot: "juggernaut",
  Varus: ["marksman", "artillery"],
  Vayne: "marksman",
  Veigar: "burst",
  VelKoz: "artillery",
  Vex: "burst",
  Vi: "diver",
  Viego: "skirmisher",
  Viktor: "battlemage",
  Vladimir: "battlemage",
  Volibear: "juggernaut",
  Warwick: "diver",
  Xayah: "marksman",
  Xerath: "artillery",
  XinZhao: "diver",
  Yasuo: "skirmisher",
  Yone: ["assassin", "skirmisher"],
  Yorick: "juggernaut",
  Yuumi: "enchanter",
  Zac: "vanguard",
  Zed: "assassin",
  Zeri: "marksman",
  Ziggs: "artillery",
  Zilean: ["enchanter", "burst"],
  Zoe: "burst",
  Zyra: "battlemage",
};
